# Generated by Django 5.0.9 on 2024-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.FloatField(default=0)),
                ('input2', models.FloatField(default=0)),
                ('input3', models.FloatField(default=0)),
            ],
        ),
    ]
