# Generated by Django 5.0.9 on 2024-11-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
