# Generated by Django 5.0.9 on 2024-12-09 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_inputtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapp.group'),
        ),
    ]
