# Generated by Django 5.0.9 on 2024-11-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_group_email_group_joined_date_group_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='passport',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
