# Generated by Django 5.0.9 on 2024-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_group_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='about',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
