# Generated by Django 5.0.9 on 2024-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_group_dob_group_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.CharField(max_length=7000, null=True),
        ),
    ]
