# Generated by Django 5.0.9 on 2024-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_alter_group_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
