# Generated by Django 5.0.9 on 2024-11-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_alter_group_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='about',
            new_name='About',
        ),
    ]
