# Generated by Django 5.0.9 on 2024-11-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_rename_about_group_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='About',
        ),
    ]
