# Generated by Django 5.0.9 on 2024-11-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_remove_group_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='About',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
