# Generated by Django 5.0.9 on 2024-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_group_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='About',
            field=models.TextField(null=True),
        ),
    ]
