# Generated by Django 5.0.9 on 2024-12-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_alter_group_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='DOB',
        ),
    ]
