# Generated by Django 5.0.9 on 2024-12-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0012_remove_group_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='About',
        ),
    ]
